image: gitlab.fi.muni.cz:5050/pb162/2023-hw02-messaging/ci:1.0

build:
  script:
    - ./mvnw clean install -B
  artifacts:
    reports:
      junit: target/surefire-reports/**/TEST-*.xml
  tags:
    - shared-fi

